<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Course_Management_Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-15T01:27:29</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b9b0683d-28e8-4256-be59-952266083911</testSuiteGuid>
   <testCaseLink>
      <guid>967e9630-9560-4b7a-9ea0-d8346820664a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Course_Management/Add_Course</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd7d7dde-0af9-4139-ae88-ce9924547d79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce6292e2-17d6-4073-aa99-595de6f6a0e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e019581-2f65-4e3f-9707-bb995ad8287f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Course_Management/Edit_Course</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45c1d180-7c11-4871-9f33-ed66a78227fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eef94c6e-550a-4133-b633-c96137beb66c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be02e449-9e3f-4e6b-8d6d-87256450f3f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Course_Management/Delete_Course</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf016c66-e886-4d84-845a-d2c4c0e671cc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
