<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Description</name>
   <tag></tag>
   <elementGuidId>6479b60d-f58b-4f02-910b-103bc2c6be6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[@class='container']/div[@class='container-fluid']/div[@class='panel']/form/div[@class='panel-body']/div[@class='form-group'][2]/textarea[@id='Description']</value>
   </webElementProperties>
</WebElementEntity>
