<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>/html/body/div[@class='container']/div[@class='container-fluid']/div[@class='panel']/form/div[@class='panel-body']/div[@class='form-group'][3]/span[@class='field-validation-error']</description>
   <name>Validate_Section</name>
   <tag></tag>
   <elementGuidId>5e620289-1fbf-4c01-9e63-0723a23385c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[@class='container']/div[@class='container-fluid']/div[@class='panel']/form/div[@class='panel-body']/div[@class='form-group'][3]/span[@class='field-validation-error']</value>
   </webElementProperties>
</WebElementEntity>
